version: '3'
services:
  kongdb:
    image: postgres:9.6
    environment:
      POSTGRES_USER : kong
      POSTGRES_DB : kong
      POSTGRES_PASSWORD : kongpass
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 30s
      timeout: 30s
      retries: 3

  kongmigrations:
    depends_on:
      - kongdb
    image: kong:2.7.1-alpine
    environment:
      KONG_DATABASE : postgres
      KONG_PG_HOST: kongdb
      KONG_PG_PASSWORD : kongpass
    command: kong migrations bootstrap
    restart: on-failure

  kong:
    depends_on:
      - kongdb
      - kongmigrations
    image: kong:2.7.1-alpine
    # image: kong:oidc
    environment:
      - "KONG_DATABASE=postgres"
      - "KONG_PG_HOST=kongdb"
      - "KONG_PG_USER=kong"
      - "KONG_PG_PASSWORD=kongpass"
      - "KONG_PROXY_ACCESS_LOG=/dev/stdout" 
      - "KONG_ADMIN_ACCESS_LOG=/dev/stdout" 
      - "KONG_PROXY_ERROR_LOG=/dev/stderr" 
      - "KONG_ADMIN_ERROR_LOG=/dev/stderr" 
      - "KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl" 
    ports:
      - "8000:8000"
      - "8443:8443"
      - "127.0.0.1:8001:8001"
      - "127.0.0.1:8444:8444"
    restart: on-failure
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10

  konga-prepare:
    image: pantsel/konga:latest
    command: "-c prepare -a postgres -u postgresql://kong:kongpass@kongdb:5432/konga"    
    restart: on-failure
    depends_on:
      - kongdb
  konga:
    image: pantsel/konga:latest
    restart: on-failure
    environment:
      DB_ADAPTER: postgres
      DB_URI: postgresql://kong:kongpass@kongdb:5432/konga
      NODE_ENV: production
    depends_on:
      - kongdb
      - konga-prepare
    ports:
      - "1337:1337"

  httpbin:
    image: kennethreitz/httpbin
    restart: on-failure
    ports:
      - "8880:80"
  
  keycloak:
    image: keycloak:dev
    environment:
      KEYCLOAK_ADMIN: admin 
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    restart: on-failure
    ports:
      - "8080:8080"